package com.techtalentsouth.TechTalentBlog.BlogPost;

import java.math.BigInteger;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class BlogPost {

    //sets the Id as the Primary Key
    @Id
	
    //allows the Id to be generated by the underlying database
    @GeneratedValue(strategy=GenerationType.AUTO)
    private BigInteger id;
	
    public BigInteger getId() {
		return id;
	}


	public void setId(BigInteger id) {
		this.id = id;
	}

	private String title;
    private String author;
    private String blogEntry;

    public BlogPost(){
        //non-argument constructor needed for JPA
    }
	

    public BlogPost(String title, String author, String blogEntry) {
	this.title = title; 
	this.author = author;
	this.blogEntry = blogEntry;
    }

    public String getTitle() {
	return title;
    }

    public void setTitle(String title) {
	this.title = title;
    }

    public String getAuthor() {
	return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getBlogEntry() {
	return blogEntry;
    }

    public void setBlogEntry(String blogEntry) {
        this.blogEntry = blogEntry;
    }

    @Override
    public String toString() {
	return "BlogPost [id=" + id + ", title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
    }
}

//package com.techtalentsouth.TechTalentBlog.BlogPost;
//
//import java.math.BigInteger;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.Table;
//
//@Entity
//@Table(name = "Blog_Post")
//public class BlogPost {
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	public BigInteger id;
//	
//	@Column(name = "Title")
//	private String title;
//	
//	@Column(name = "Author")
//	private String author;
//	
//	@Column(name = "Blog_Entry")
//	private String blogEntry;
//
//	public BlogPost() {
//		// non-argument constructor needed for JPA
//	}
//
//	public BlogPost(BigInteger id, String title, String author, String blogEntry) {
//		this.id = id;
//		this.title = title;
//		this.author = author;
//		this.blogEntry = blogEntry;
//	}
//	
//
//	public BigInteger getID() {
//		return id;
//	}
//	
//	public void setID(BigInteger id) {
//		this.id = id;
//	}
//	
//	public String getTitle() {
//		return title;
//	}
//
//	public void setTitle(String title) {
//		this.title = title;
//	}
//
//	public String getAuthor() {
//		return author;
//	}
//
//	public void setAuthor(String author) {
//		this.author = author;
//	}
//
//	public String getBlogEntry() {
//		return blogEntry;
//	}
//
//	public void setBlogEntry(String blogEntry) {
//		this.blogEntry = blogEntry;
//	}
//
//	@Override
//	public String toString() {
//		return "BlogPost [id=" + id + ", title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
//	}
//}